baseURL = "https://sysarmy.com/blog/"
languageCode = "en-us"
title = "El blog de quienes dan soporte"
theme = "sysarmy"
publishDir = "/"
MetaDataFormat = "toml"
#googleAnalytics = "UA-36359098-1"

footnoteReturnLinkContents = ":leftwards_arrow_with_hook:"

[author]
    name = "Sysarmy"
