name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - master

jobs:
  hugo-deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: hugo-deploy-gh-pages
      uses: khanhicetea/gh-actions-hugo-deploy-gh-pages@master
      env:
        GITHUB_BRANCH: gh-pages
        GIT_DEPLOY_KEY: ${{ secrets.GIT_DEPLOY_KEY }}
        HUGO_VERSION: "0.80.0"

  update-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - with:
          repository: sysarmy/sysarmy.github.io
          ssh-key: ${{ secrets.SYSARMYDEPLOYKEY }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd blog
          git submodule update --init --recursive
          git checkout gh-pages
          git pull
          cd ..
          git commit -m "Automated deployment to GitHub Pages for commit: ${{ github.sha }}"
          git push