# This is a basic workflow to help you get started with Actions

name: update submodule in remote website
# Controls when the action will run. 
on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types: [completed]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  update-submodule:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with:
        repository: sysarmy/sysarmy.github.io
        ref: master
        ssh-key: ${{ secrets.SYSARMYDEPLOYKEY }}
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com 
        git submodule update --init --recursive
        git submodule update --remote
        git add . 
        git commit -m "Automated deployment to GitHub Pages for commit: ${{ github.sha }}" 
        git push
